query getOrder($input:GetOrderInput){
  getOrder(input:$input){
    code
    success
    message
    order{
      id
      createdAt
      orderType
      orderStatus
      deliveryStatus
      orderNote
      deliveryCharge
      prepareTime
      orderAddress{
        name
        phoneNo
        address
        email
        city
        country
        postalCode
        organizationNo
      }
      orderBy{
        firstName
        lastName
        email
      }
      items{
        id
        cartItems{
          productId
          productName
          pricePerUnit
          productQuantity
          qtyPerBox
          productSize
        }
        totalCost
      }
    }
  }
}